---

- hosts: all
  vars:
      gitlab_hostname: gitlab.agoravoting.com
      gitlab_passwd: secret

  tasks:
    - name: installing packages
      sudo: true
      apt: pkg={{ item }} state=present update_cache=yes
      with_items:
        - curl
        - openssh-server
        - ca-certificates
        - postfix
        - ruby2.0

    - name: getting the package
      get_url: url=https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/trusty/gitlab-ce_8.3.2-ce.0_amd64.deb/download dest=/tmp/gitlab.deb mode=0440

    - name: installing the package
      sudo: true
      shell: dpkg -i /tmp/gitlab.deb

    - name: configuring external url
      sudo: true
      lineinfile: dest=/etc/gitlab/gitlab.rb regexp="^external_url" line="external_url 'https://{{ gitlab_hostname }}'"

    - name: configuring external url
      sudo: true
      lineinfile: dest=/etc/gitlab/gitlab.rb line="{{ item }}"
      with_items:
        - "gitlab_rails['initial_root_password'] = '{{ gitlab_passwd }}'"
        - "nginx['redirect_http_to_https'] = true"

    - name: cert directories creation
      sudo: true
      file: path=/etc/gitlab/ssl/ recurse=yes state=directory owner=root group=www-data

    - name: self-signed certificate creation script
      template: src=cert.sh dest=/tmp/cert.sh mode=0777

    - name: self-signed certificate creation
      sudo: true
      shell: "/tmp/cert.sh"

    - name: configuring gitlab
      sudo: true
      shell: gitlab-ctl reconfigure
